// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQE6gw1e81C9kM7dO_DqZO2bMAtchctyk',
    appId: '1:443316802856:web:1b37d188316f0beecf2c1d',
    messagingSenderId: '443316802856',
    projectId: 'crud-2acff',
    authDomain: 'crud-2acff.firebaseapp.com',
    storageBucket: 'crud-2acff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDnJi6R1RvHzdmQyHXXQ-P5aWEzvVCM2k',
    appId: '1:443316802856:android:3ed1ef871ed7da99cf2c1d',
    messagingSenderId: '443316802856',
    projectId: 'crud-2acff',
    storageBucket: 'crud-2acff.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQE6gw1e81C9kM7dO_DqZO2bMAtchctyk',
    appId: '1:443316802856:web:1b37d188316f0beecf2c1d',
    messagingSenderId: '443316802856',
    projectId: 'crud-2acff',
    authDomain: 'crud-2acff.firebaseapp.com',
    storageBucket: 'crud-2acff.firebasestorage.app',
  );

}